# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f46c8009e711b3cb086b9bfaacd9a3687ac8855a62cf9f515b601d703a26021706eb7c98af8abd6374914e458055872df1621e02bc94f46f823fe4209957cbdd

test:
  secret_key_base: 71a61c7a4810c95dff4830a05beb2621e343b1d1f7389df42237296e3a08d80289cc0dd6e6fafbdd8e4ad50c426f664c04869c459a67a6ca1075f285f5bbf4fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
